In [1]:
import numpy as np

In [2]:
max  = np.ones(20).reshape(4,5)

In [3]:
print(max)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
print(max[1][1])

1.0


In [1]:
import serial

AttributeError: partially initialized module 'serial' has no attribute 'Serial' (most likely due to a circular import)

In [35]:
a = [0,1,2]
b = [3,4,5]
c = [6,7,8]
d = [0,1,2]

In [36]:
for i in range(len(a)):
    print(a[i])


0
1
2
